SELECT CONCAT(NAME, '(', LEFT(OCCUPATION,1), ')')
FROM OCCUPATIONS
ORDER BY NAME

SELECT CONCAT('There are a total of ', CAST(COUNT(*) AS CHAR), LOWER(OCCUPATION), 's.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY CONCAT('There are a total of ', CAST(COUNT(*) AS CHAR), LOWER(OCCUPATION), 's.')